# Generated by Django 6.0.1 on 2026-01-07 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_alter_person_options_person_dedup_key_and_more'),
        ('webforms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('external_id', models.CharField(max_length=255)),
                ('dedup_key', models.CharField(blank=True, db_index=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(unique=True)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('dedup_key', models.CharField(blank=True, db_index=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='webformsubmission',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='webformsubmission',
            name='webform_name',
        ),
        migrations.AddField(
            model_name='webformsubmission',
            name='dedup_key',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='webformsubmission',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='webformsubmission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='webformsubmission',
            name='source_website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='webformsubmission',
            name='webform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='webforms.webform'),
        ),
        migrations.AddIndex(
            model_name='webformsubmission',
            index=models.Index(fields=['webform', 'external_id'], name='webforms_we_webform_b93fe2_idx'),
        ),
        migrations.AddIndex(
            model_name='webformsubmission',
            index=models.Index(fields=['person', 'created_at'], name='webforms_we_person__2fe727_idx'),
        ),
        migrations.AddIndex(
            model_name='website',
            index=models.Index(fields=['url'], name='webforms_we_url_0eb46c_idx'),
        ),
        migrations.AddIndex(
            model_name='website',
            index=models.Index(fields=['external_id'], name='webforms_we_externa_7253d0_idx'),
        ),
        migrations.AddField(
            model_name='webform',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webforms', to='webforms.website'),
        ),
        migrations.AddIndex(
            model_name='webform',
            index=models.Index(fields=['website', 'external_id'], name='webforms_we_website_79d5b9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='webform',
            unique_together={('website', 'external_id')},
        ),
    ]
