# Generated by Django 6.0.1 on 2026-01-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='person',
            name='dedup_key',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='person',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['email'], name='persons_per_email_53cfea_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['external_id'], name='persons_per_externa_97c46f_idx'),
        ),
    ]
