# Generated by Django 6.0.1 on 2026-01-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_person_country_person_domain_person_organisation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='webform',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
